#apiVersion: v1
#kind: Secret
#metadata:
#    name: dingo-es-tls
#    namespace: default
#data:
#    tls.crt: base64 encoded cert
#    tls.key: base64 encoded key
#type: kubernetes.io/tls
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
    name: $K8S_CERT_NAME
spec:
    domains:
    - $K8S_ES_INGRESS_DOMAINS
    - $K8S_ES_COODR_DOMAINS
    - $K8S_ES_KIBANA_DOMAINS
